### ISSUE TITLE
Scoring for Indels

### ISSUE THREAD

**Issue by JIBINJOHNV** [AldisiRana/GenRisk#1]
For some frameshift and non-frameshift variants, CADD scores are not available when we annotate the vcf files with vep. In that case, how is the scoring (weighting) conducted?

**Comment by AldisiRana** [comment]
Our scores are general, that is, you can choose whatever deleteriousness or weighting score you want to use to score the genes. We use CADD in our examples because mainly our analysis focuses on point mutations. After you annotate your vcf with whatever weighting score you wish to use on your variants, you can specify the weighting score present in your vcf by using the (--del-col) argument in the (genrisk score-genes) command.
